//
//  Day7Tests.swift
//  AdventOfCode
//
//  Created by Kamaal M Farah on 12/07/25.
//

import Testing
import KamaalExtensions
@testable import AdventOfCode2025

private let day7 = Day7()

@Test func `Day 7 Part 1 Example 1`() async throws {
    let example = """
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
    """

    let solution = try await day7.solvePart1(example).int

    #expect(solution == 21)
}

@Test func `Day 7 Part 1`() async throws {
    let solution = try await day7.solvePart1(nil).int

    #expect(solution == 1560)
}

@Test func `Day 7 Part 2 Example 1`() async throws {
    let example = """
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
    """

    let solution = try await day7.solvePart2(example).int

    #expect(solution == 0)
}

@Test func `Day 7 Part 2`() async throws {
    let solution = try await day7.solvePart2(nil).int

    #expect(solution == 0)
}
